# Generated by Django 2.0.3 on 2018-04-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180407_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
    ]
