# Generated by Django 2.0.3 on 2018-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
