# Generated by Django 2.0.3 on 2018-04-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20180408_0246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='subjects',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(blank=True, choices=[('---', '---'), ('CSE', 'Computer Science & Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('MECH', 'Mechanical Engineering'), ('MME', 'Metallurgy Engineering'), ('CHE', 'Chemical Engineering'), ('CIVIL', 'Civil Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('BIO', 'Biotechnology')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th')], max_length=20, null=True),
        ),
    ]
