# Generated by Django 2.0.3 on 2018-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('AC', 'Academics'), ('CA', 'Clubs and Associations'), ('GN', 'General'), ('CR', 'Class Representative')], default='AC', max_length=2),
        ),
    ]
