# Generated by Django 2.0.3 on 2018-04-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180403_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('AC', 'Academics'), ('CA', 'Clubs and Associations'), ('GN', 'General'), ('CR', 'Class Representative'), ('SP', 'Sports')], default='AC', max_length=2),
        ),
    ]
