# Generated by Django 2.0.3 on 2018-04-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_signup_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subjectid', models.TextField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('classType', models.TextField()),
            ],
        ),
    ]
