# Generated by Django 2.0.3 on 2018-04-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='date',
            field=models.TextField(),
        ),
    ]
