# Generated by Django 2.0.3 on 2018-04-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20180407_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AS', 'Assignments'), ('PR', 'Previous Papers'), ('NO', 'notes')], default='AS', max_length=2)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('GN', 'General'), ('CR', 'Class Representative')], default='GN', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='subject',
            name='assignments',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='prevpapers',
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Subject'),
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Subject'),
        ),
    ]
