# Generated by Django 2.0.3 on 2018-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_auto_20180407_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='category',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.TextField(),
        ),
    ]
