# Generated by Django 2.0.3 on 2018-04-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0010_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
    ]
