# Generated by Django 2.0.3 on 2018-04-07 16:35

from django.db import migrations, models
import django.db.models.deletion
import feed.models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20180407_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AS', 'Assignment'), ('NO', 'Notes'), ('PP', 'Previous Papers')], max_length=2)),
                ('file', models.FileField(upload_to=feed.models.get_material_file_path)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='material', to='feed.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=feed.models.get_post_image_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='feed.Post'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Course'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
