# Generated by Django 2.0.3 on 2018-04-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_auto_20180407_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
